/*LOS CONDICIONALES SIRVEN PARA PODER PREGUNTAR EN UNA MISMA PREGUNTA, O EN UN MISMO IF VARIAS COSAS AL MISMO TIEMPO.
ESTO SE CONSIGUE MEDIANTE EL USO DEL &&(Y) Y DEL ||(O)

EL FUNCIONAMIENTO DEL && ES DEL SIGUIENTE MODO: PARA QUE LA PREGUNTA ME DÉ COMO RESULTADO VERDAD, TIENEN QUE CUMPLIRSE TODAS LAS CONDICIONES.

EL FUNCIONAMIENTO DEL ||(O) ES DEL SIGUIENTE MODO: PARA QUE LA PREGUNTA ME DÉ COMO RESULTADO VERDAD, CON QUE SOLO SE CUMPLA UNA DE LAS CONDICIONES, 
EL RESULTADO SERA VERDAD. */

#include <iostream>

using namespace std;

int main()
{
    int a=10;
    int b=20;
    int c=30;
    int d=60;
    
    if(a==10 || b==20 || c==30 || d==10)
    {
             cout<<"Todas las condiciones son verdad"<<endl;
    }
    system("pause");
}
